name: Cypress Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    env:
        SAUCEDEMO_USERNAME: ${{ secrets.SAUCEDEMO_USERNAME }}
        SAUCEDEMO_PASSWORD: ${{ secrets.SAUCEDEMO_PASSWORD }}
        PARABANK_USERNAME: ${{ secrets.PARABANK_USERNAME }}
        PARABANK_PASSWORD: ${{ secrets.PARABANK_PASSWORD }}
        ORANGEHRM_USERNAME: ${{ secrets.ORANGEHRM_USERNAME }}
        ORANGEHRM_PASSWORD: ${{ secrets.ORANGEHRM_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run

